!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn:
- mHandle: 0
  mName: Analog In 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiAnalogInWrapper
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO:
- mHandle: 1
  mName: Digital 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders: []
mGyros: []
mPwm: []
mRelays: []
mSimulatorComponents: []
